<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Crm.Application\Crm.Application.csproj" />
    <ProjectReference Include="..\Crm.Entity\Crm.Entity.csproj" />
    <ProjectReference Include="..\Crm.Infrastructure\Crm.Infrastructure.csproj" />
    <PackageReference Include="DevExtreme.AspNet.Core" Version="22.2.5" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\js\company\" />
  </ItemGroup>
</Project>